# Generated by Django 2.2.1 on 2022-10-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
