# Generated by Django 2.2.1 on 2022-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_org', models.BooleanField(default=False, verbose_name='is org')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is student')),
                ('is_alumni', models.BooleanField(default=False, verbose_name='is alumni')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
