# Generated by Django 2.2.1 on 2022-11-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
