# Generated by Django 2.2.1 on 2022-11-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
