# Generated by Django 2.2.1 on 2022-11-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_orgsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgsettings',
            old_name='profileimg',
            new_name='orgimg',
        ),
    ]
