# Generated by Django 4.1.3 on 2022-11-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_friend"),
    ]

    operations = [
        migrations.DeleteModel(name="Friend",),
    ]
